"""
workers/base_worker.py — Orbit Worker Roles (Phase 4)
======================================================
PRD §3.2, §4.3, §4.4:
  "Implement 3 worker roles (backend, frontend, database) as functions that
   take a TaskContract, call Ollama (same model for all three per Stage A in
   Section 4.3), use the Phase 3 tool gateway to edit files, and return an
   artifact plus status."

Worker Roles:
  - BackendWorker  (role: "backend")  — core functions, modules, algorithms, tests
  - FrontendWorker (role: "frontend") — CLI interfaces, presentation, templates, views
  - DatabaseWorker (role: "database") — schemas, models, queries, migrations

Each worker:
  1. Operates inside contract.allowed_workspace via ToolGateway.
  2. Seeds its workspace with target repo files and upstream dependency artifacts.
  3. Reads relevant inputs via gateway.read_file().
  4. Calls Ollama with role-specific system prompt requesting JSON file changes.
  5. Applies file writes strictly through ToolGateway (enforcing PathEscapeError and MAX_TOOL_CALLS).
  6. Executes tests if present via gateway.run_tests().
  7. Updates TaskContract with status, result_summary, and evidence dict.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import shutil
import textwrap
import time
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, Callable

from architect.architect import call_ollama, extract_json
from gateway.gateway import (
    PathEscapeError,
    TestTimeoutError,
    ToolBudgetExhausted,
    ToolGateway,
)
from models.spec import FailureContext, TaskContract, TaskStatus, WorkerRole

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Role System Prompts
# ---------------------------------------------------------------------------

_ROLE_PROMPTS: dict[str, str] = {
    "backend": textwrap.dedent("""\
        You are the Backend Worker in Orbit, an autonomous multi-agent software engineering harness.
        Your role is to write clean, type-annotated, idiomatic backend code, algorithms, services,
        data structures, and tests according to the given TaskContract.
        Focus on correctness, edge cases, type annotations, and matching the existing repository style.
    """),
    "frontend": textwrap.dedent("""\
        You are the Frontend Worker in Orbit, an autonomous multi-agent software engineering harness.
        Your role is to implement user interfaces, CLI commands, formatting, templates, client-facing
        APIs, and view components according to the given TaskContract.
        Ensure clean presentation, proper parameter handling, and seamless integration with backend modules.
    """),
    "database": textwrap.dedent("""\
        You are the Database Worker in Orbit, an autonomous multi-agent software engineering harness.
        Your role is to design and implement database schemas, data models, persistence routines,
        migrations, and queries according to the given TaskContract.
        Ensure data integrity, correct schemas, and safe operations.
    """),
}


# ---------------------------------------------------------------------------
# Workspace Initialization Helper
# ---------------------------------------------------------------------------

def seed_workspace(
    workspace_root: Path,
    target_dir: Path | None = None,
    upstream_workspaces: list[Path] | None = None,
) -> None:
    """
    Seed an isolated worker workspace with the baseline target directory files
    and any artifacts generated by completed upstream dependencies.
    """
    workspace_root.mkdir(parents=True, exist_ok=True)

    # 1. Copy baseline target files (skipping VCS and cache dirs)
    if target_dir and target_dir.exists():
        for src in target_dir.rglob("*"):
            if src.is_dir():
                continue
            rel = src.relative_to(target_dir)
            # Skip hidden / vcs / caches
            parts = rel.parts
            if any(p.startswith(".") or p in ("__pycache__", "venv", ".venv") for p in parts):
                continue
            dest = workspace_root / rel
            if not dest.exists():
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dest)

    # 2. Overlay upstream dependency artifacts / files if provided
    if upstream_workspaces:
        for up_ws in upstream_workspaces:
            if not up_ws.exists():
                continue
            for src in up_ws.rglob("*"):
                if src.is_dir():
                    continue
                rel = src.relative_to(up_ws)
                parts = rel.parts
                if any(p.startswith(".") or p in ("__pycache__",) for p in parts):
                    continue
                dest = workspace_root / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dest)


# ---------------------------------------------------------------------------
# BaseWorker Class
# ---------------------------------------------------------------------------

class BaseWorker(ABC):
    """Abstract base for all Orbit worker roles."""

    role: str = "base"

    def __init__(
        self,
        model: str = "nemotron-3-ultra:cloud",
        gateway: ToolGateway | None = None,
        base_url: str = "http://localhost:11434",
        target_dir: Path | None = None,
        upstream_workspaces: list[Path] | None = None,
        ollama_caller: Callable[..., tuple[str, int, int]] | None = None,
    ) -> None:
        self.model = model
        self.gateway = gateway
        self.base_url = base_url
        self.target_dir = Path(target_dir).resolve() if target_dir else None
        self.upstream_workspaces = [Path(p).resolve() for p in (upstream_workspaces or [])]
        self._call_ollama = ollama_caller or call_ollama

    def _build_worker_prompt(
        self,
        contract: TaskContract,
        gateway: ToolGateway,
        previous_error: str = "",
    ) -> str:
        """Construct the prompt sent to the LLM for this task contract."""
        lines = [
            f"TASK OBJECTIVE:\n{contract.objective}\n",
            f"ROLE: {contract.role}\n",
            f"EXPECTED ARTIFACT: {contract.expected_artifact}\n",
        ]
        if contract.acceptance_criteria:
            lines.append("ACCEPTANCE CRITERIA:")
            for ac in contract.acceptance_criteria:
                lines.append(f"  - {ac}")
            lines.append("")

        if contract.style_guide:
            lines.append(f"STYLE GUIDE:\n{contract.style_guide}\n")

        # Read available input files
        input_contents: list[str] = []
        for inp in contract.inputs:
            try:
                # Try reading relative to workspace first, or target_dir
                path_to_read = inp
                if not Path(inp).is_absolute():
                    candidate = gateway.workspace_root / inp
                    if candidate.exists():
                        path_to_read = str(candidate)
                    elif self.target_dir and (self.target_dir / inp).exists():
                        path_to_read = str(self.target_dir / inp)

                content = gateway.read_file(path_to_read)
                input_contents.append(f"--- File: {inp} ---\n{content}\n")
            except Exception:
                # File may not exist yet if it's an output to create
                pass

        if input_contents:
            lines.append("RELEVANT EXISTING FILES CONTENT:")
            lines.extend(input_contents)

        failure_ctx = contract.evidence.get("failure_context")
        if failure_ctx:
            lines.append("\nTARGETED REWORK PASS (FIXING TEST FAILURE):")
            lines.append(f"Failing Command : {failure_ctx.get('command', '')}")
            lines.append(f"Error Output    :\n{failure_ctx.get('error_output', '')}\n")
            if failure_ctx.get("stack_trace"):
                lines.append(f"Stack Trace     :\n{failure_ctx.get('stack_trace', '')}\n")
            if failure_ctx.get("changed_files"):
                lines.append(f"Files To Fix    : {failure_ctx.get('changed_files', [])}\n")
            lines.append("Provide the corrected file content to resolve this failure.\n")

        if previous_error:
            lines.append(
                f"YOUR PREVIOUS RESPONSE FAILED WITH THIS ERROR:\n"
                f"{previous_error}\n"
                f"Fix the JSON response and return ONLY the corrected JSON object.\n"
            )

        lines.append(textwrap.dedent("""\
            INSTRUCTIONS:
            1. Provide the complete implementation files required to fulfill the objective and expected artifact.
            2. Return ONLY a single JSON object matching this schema:
            {
              "summary": "<1-2 sentence description of what was implemented>",
              "files": [
                {
                  "path": "<relative path within workspace, e.g. src/greeter.py or tests/test_greeter.py>",
                  "content": "<complete source code content for the file>"
                }
              ]
            }
            Do NOT wrap in markdown explanations outside the JSON. Return ONLY the JSON object.
        """))
        return "\n".join(lines)

    def execute(self, contract: TaskContract) -> TaskContract:
        """
        Run the task described in *contract* and return the updated contract.
        Uses ToolGateway for all file writes and test runs.
        """
        contract.status = TaskStatus.RUNNING
        workspace_path = Path(contract.allowed_workspace).resolve()

        # 1. Initialize ToolGateway for this worker's workspace
        if self.gateway is None:
            seed_workspace(workspace_path, self.target_dir, self.upstream_workspaces)
            gateway = ToolGateway(workspace_root=workspace_path)
        else:
            gateway = self.gateway
            workspace_path = gateway.workspace_root
            seed_workspace(workspace_path, self.target_dir, self.upstream_workspaces)

        system_prompt = _ROLE_PROMPTS.get(self.role, _ROLE_PROMPTS["backend"])

        # 2. Call Ollama with retry
        prompt = self._build_worker_prompt(contract, gateway)
        attempt_error = ""
        parsed_data: dict[str, Any] | None = None
        total_tok_in = 0
        total_tok_out = 0

        for attempt in (1, 2):
            try:
                curr_prompt = prompt if attempt == 1 else self._build_worker_prompt(contract, gateway, previous_error=attempt_error)
                raw_resp, tok_in, tok_out = self._call_ollama(
                    prompt=curr_prompt,
                    system=system_prompt,
                    model=self.model,
                    base_url=self.base_url,
                    temperature=0.0,
                )
                total_tok_in += tok_in
                total_tok_out += tok_out

                json_str = extract_json(raw_resp)
                parsed = json.loads(json_str)
                if not isinstance(parsed, dict) or "files" not in parsed:
                    raise ValueError(f"Response must be a JSON object with a 'files' list. Got: {json_str[:200]}")
                parsed_data = parsed
                break
            except Exception as exc:
                attempt_error = str(exc)
                if attempt == 2:
                    contract.status = TaskStatus.FAILED
                    contract.result_summary = f"Worker failed to obtain valid file edits from LLM: {attempt_error}"
                    contract.evidence = {
                        "error": attempt_error,
                        "tokens_in": total_tok_in,
                        "tokens_out": total_tok_out,
                    }
                    return contract

        assert parsed_data is not None
        summary_text = parsed_data.get("summary", f"Completed {contract.role} task: {contract.objective}")
        files_to_write = parsed_data.get("files", [])

        # 3. Apply file writes through ToolGateway
        written_paths: list[str] = []
        try:
            for item in files_to_write:
                rel_path = item.get("path", "").strip()
                content = item.get("content", "")
                if not rel_path:
                    continue
                p = Path(rel_path)
                # Only remap safe relative paths without directory traversal
                if not p.is_absolute() and ".." not in p.parts:
                    if self.target_dir and not (self.target_dir / p).exists():
                        fname = p.name
                        matches = [
                            f for f in self.target_dir.rglob(fname)
                            if not any(part.startswith(".") for part in f.parts)
                        ]
                        if len(matches) == 1:
                            rel_path = str(matches[0].relative_to(self.target_dir))

                gateway.write_file(rel_path, content)
                written_paths.append(rel_path)
        except PathEscapeError as exc:
            contract.status = TaskStatus.FAILED
            contract.result_summary = f"PathEscapeError blocked: {exc}"
            contract.evidence = {
                "error": "PathEscapeError",
                "detail": str(exc),
                "gateway_summary": gateway.summary(),
            }
            return contract
        except ToolBudgetExhausted as exc:
            contract.status = TaskStatus.FAILED
            contract.result_summary = f"ToolBudgetExhausted: {exc}"
            contract.evidence = {
                "error": "ToolBudgetExhausted",
                "detail": str(exc),
                "gateway_summary": gateway.summary(),
            }
            return contract
        except Exception as exc:
            contract.status = TaskStatus.FAILED
            contract.result_summary = f"File write error: {exc}"
            contract.evidence = {
                "error": str(exc),
                "gateway_summary": gateway.summary(),
            }
            return contract

        # 4. Optional verification / test runner if tests exist in workspace
        test_output = ""
        test_passed = True
        has_tests = any(workspace_path.rglob("test_*.py")) or any(workspace_path.rglob("*_test.py"))
        if has_tests:
            try:
                test_res = gateway.run_tests(test_command="python3 -m pytest", cwd=workspace_path)
                test_passed = test_res.passed
                test_output = test_res.output
            except (TestTimeoutError, Exception) as exc:
                test_passed = False
                test_output = f"Test execution exception: {exc}"

        # 5. Populate outcome
        # If tests failed, mark FAILED; otherwise DONE
        if has_tests and not test_passed:
            contract.status = TaskStatus.FAILED
            contract.result_summary = f"Changes applied but tests failed: {summary_text}"
        else:
            contract.status = TaskStatus.DONE
            contract.result_summary = summary_text

        contract.evidence = {
            "files_written": written_paths,
            "has_tests": has_tests,
            "test_passed": test_passed,
            "test_output": test_output[-2000:] if test_output else "",
            "tokens_in": total_tok_in,
            "tokens_out": total_tok_out,
            "gateway_summary": gateway.summary(),
        }
        return contract

    def recover(self, contract: TaskContract, ctx: FailureContext) -> TaskContract:
        """Targeted recovery pass. Incorporates FailureContext to fix failure."""
        contract.evidence["failure_context"] = ctx.model_dump()
        return self.execute(contract)


# ---------------------------------------------------------------------------
# Concrete Worker Classes
# ---------------------------------------------------------------------------

class BackendWorker(BaseWorker):
    role = "backend"


class FrontendWorker(BaseWorker):
    role = "frontend"


class DatabaseWorker(BaseWorker):
    role = "database"


# ---------------------------------------------------------------------------
# Functional Worker Interfaces
# ---------------------------------------------------------------------------

_ROLE_MAP: dict[str, type[BaseWorker]] = {
    "backend": BackendWorker,
    "frontend": FrontendWorker,
    "database": DatabaseWorker,
}


def run_worker(
    contract: TaskContract,
    gateway: ToolGateway | None = None,
    model: str = "nemotron-3-ultra:cloud",
    base_url: str = "http://localhost:11434",
    target_dir: Path | None = None,
    upstream_workspaces: list[Path] | None = None,
    ollama_caller: Callable[..., tuple[str, int, int]] | None = None,
) -> TaskContract:
    """Synchronous worker execution function."""
    role_key = contract.role.value if hasattr(contract.role, "value") else str(contract.role)
    worker_cls = _ROLE_MAP.get(role_key.lower(), BackendWorker)
    worker = worker_cls(
        model=model,
        gateway=gateway,
        base_url=base_url,
        target_dir=target_dir,
        upstream_workspaces=upstream_workspaces,
        ollama_caller=ollama_caller,
    )
    return worker.execute(contract)


def run_backend_worker(
    contract: TaskContract,
    gateway: ToolGateway | None = None,
    model: str = "nemotron-3-ultra:cloud",
    base_url: str = "http://localhost:11434",
    target_dir: Path | None = None,
    upstream_workspaces: list[Path] | None = None,
    ollama_caller: Callable[..., tuple[str, int, int]] | None = None,
) -> TaskContract:
    worker = BackendWorker(
        model=model,
        gateway=gateway,
        base_url=base_url,
        target_dir=target_dir,
        upstream_workspaces=upstream_workspaces,
        ollama_caller=ollama_caller,
    )
    return worker.execute(contract)


def run_frontend_worker(
    contract: TaskContract,
    gateway: ToolGateway | None = None,
    model: str = "nemotron-3-ultra:cloud",
    base_url: str = "http://localhost:11434",
    target_dir: Path | None = None,
    upstream_workspaces: list[Path] | None = None,
    ollama_caller: Callable[..., tuple[str, int, int]] | None = None,
) -> TaskContract:
    worker = FrontendWorker(
        model=model,
        gateway=gateway,
        base_url=base_url,
        target_dir=target_dir,
        upstream_workspaces=upstream_workspaces,
        ollama_caller=ollama_caller,
    )
    return worker.execute(contract)


def run_database_worker(
    contract: TaskContract,
    gateway: ToolGateway | None = None,
    model: str = "nemotron-3-ultra:cloud",
    base_url: str = "http://localhost:11434",
    target_dir: Path | None = None,
    upstream_workspaces: list[Path] | None = None,
    ollama_caller: Callable[..., tuple[str, int, int]] | None = None,
) -> TaskContract:
    worker = DatabaseWorker(
        model=model,
        gateway=gateway,
        base_url=base_url,
        target_dir=target_dir,
        upstream_workspaces=upstream_workspaces,
        ollama_caller=ollama_caller,
    )
    return worker.execute(contract)


async def run_worker_async(
    contract: TaskContract,
    gateway: ToolGateway | None = None,
    model: str = "nemotron-3-ultra:cloud",
    base_url: str = "http://localhost:11434",
    target_dir: Path | None = None,
    upstream_workspaces: list[Path] | None = None,
    ollama_caller: Callable[..., tuple[str, int, int]] | None = None,
) -> TaskContract:
    """Asynchronous worker execution function (runs synchronous execute in threadpool)."""
    return await asyncio.to_thread(
        run_worker,
        contract=contract,
        gateway=gateway,
        model=model,
        base_url=base_url,
        target_dir=target_dir,
        upstream_workspaces=upstream_workspaces,
        ollama_caller=ollama_caller,
    )
